/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ArduinoAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ArduinoJoin');
goog.require('proto.ArduinoWorkoutAction');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ArduinoAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ArduinoAction.oneofGroups_);
};
goog.inherits(proto.ArduinoAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ArduinoAction.displayName = 'proto.ArduinoAction';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ArduinoAction.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.ArduinoAction.MessageCase = {
  MESSAGE_NOT_SET: 0,
  ARDUINOJOIN: 1,
  ARDUINOWORKOUTACTION: 2
};

/**
 * @return {proto.ArduinoAction.MessageCase}
 */
proto.ArduinoAction.prototype.getMessageCase = function() {
  return /** @type {proto.ArduinoAction.MessageCase} */(jspb.Message.computeOneofCase(this, proto.ArduinoAction.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ArduinoAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ArduinoAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ArduinoAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArduinoAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    arduinojoin: (f = msg.getArduinojoin()) && proto.ArduinoJoin.toObject(includeInstance, f),
    arduinoworkoutaction: (f = msg.getArduinoworkoutaction()) && proto.ArduinoWorkoutAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ArduinoAction}
 */
proto.ArduinoAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ArduinoAction;
  return proto.ArduinoAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ArduinoAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ArduinoAction}
 */
proto.ArduinoAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ArduinoJoin;
      reader.readMessage(value,proto.ArduinoJoin.deserializeBinaryFromReader);
      msg.setArduinojoin(value);
      break;
    case 2:
      var value = new proto.ArduinoWorkoutAction;
      reader.readMessage(value,proto.ArduinoWorkoutAction.deserializeBinaryFromReader);
      msg.setArduinoworkoutaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ArduinoAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ArduinoAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ArduinoAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArduinoAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArduinojoin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ArduinoJoin.serializeBinaryToWriter
    );
  }
  f = message.getArduinoworkoutaction();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ArduinoWorkoutAction.serializeBinaryToWriter
    );
  }
};


/**
 * optional ArduinoJoin arduinoJoin = 1;
 * @return {?proto.ArduinoJoin}
 */
proto.ArduinoAction.prototype.getArduinojoin = function() {
  return /** @type{?proto.ArduinoJoin} */ (
    jspb.Message.getWrapperField(this, proto.ArduinoJoin, 1));
};


/** @param {?proto.ArduinoJoin|undefined} value */
proto.ArduinoAction.prototype.setArduinojoin = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.ArduinoAction.oneofGroups_[0], value);
};


proto.ArduinoAction.prototype.clearArduinojoin = function() {
  this.setArduinojoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ArduinoAction.prototype.hasArduinojoin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ArduinoWorkoutAction arduinoWorkoutAction = 2;
 * @return {?proto.ArduinoWorkoutAction}
 */
proto.ArduinoAction.prototype.getArduinoworkoutaction = function() {
  return /** @type{?proto.ArduinoWorkoutAction} */ (
    jspb.Message.getWrapperField(this, proto.ArduinoWorkoutAction, 2));
};


/** @param {?proto.ArduinoWorkoutAction|undefined} value */
proto.ArduinoAction.prototype.setArduinoworkoutaction = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ArduinoAction.oneofGroups_[0], value);
};


proto.ArduinoAction.prototype.clearArduinoworkoutaction = function() {
  this.setArduinoworkoutaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ArduinoAction.prototype.hasArduinoworkoutaction = function() {
  return jspb.Message.getField(this, 2) != null;
};


