/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ArduinoWorkoutAction');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ArduinoWorkoutAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ArduinoWorkoutAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ArduinoWorkoutAction.displayName = 'proto.ArduinoWorkoutAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ArduinoWorkoutAction.prototype.toObject = function(opt_includeInstance) {
  return proto.ArduinoWorkoutAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ArduinoWorkoutAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArduinoWorkoutAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    n: jspb.Message.getFieldWithDefault(msg, 1, 0),
    powercontract: jspb.Message.getFieldWithDefault(msg, 2, 0),
    weight: jspb.Message.getFieldWithDefault(msg, 3, 0),
    set: jspb.Message.getFieldWithDefault(msg, 4, 0),
    contract: jspb.Message.getFieldWithDefault(msg, 5, 0),
    rfidcardno: jspb.Message.getFieldWithDefault(msg, 6, 0),
    machine: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ArduinoWorkoutAction}
 */
proto.ArduinoWorkoutAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ArduinoWorkoutAction;
  return proto.ArduinoWorkoutAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ArduinoWorkoutAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ArduinoWorkoutAction}
 */
proto.ArduinoWorkoutAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setN(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPowercontract(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWeight(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSet(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setContract(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRfidcardno(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMachine(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ArduinoWorkoutAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ArduinoWorkoutAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ArduinoWorkoutAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArduinoWorkoutAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getN();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPowercontract();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSet();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getContract();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRfidcardno();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getMachine();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional int32 n = 1;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getN = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setN = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 powerContract = 2;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getPowercontract = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setPowercontract = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 weight = 3;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setWeight = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 set = 4;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getSet = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setSet = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 contract = 5;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getContract = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setContract = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 rfIdCardNo = 6;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getRfidcardno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setRfidcardno = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 machine = 7;
 * @return {number}
 */
proto.ArduinoWorkoutAction.prototype.getMachine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.ArduinoWorkoutAction.prototype.setMachine = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


