/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ServerMessage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ArduinoConnected');
goog.require('proto.ClientConnected');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ServerMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ServerMessage.oneofGroups_);
};
goog.inherits(proto.ServerMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ServerMessage.displayName = 'proto.ServerMessage';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ServerMessage.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.ServerMessage.MessageCase = {
  MESSAGE_NOT_SET: 0,
  ARDUINOCONNECTEDMESSAGE: 1,
  CLIENTCONNECTEDMESSAGE: 2
};

/**
 * @return {proto.ServerMessage.MessageCase}
 */
proto.ServerMessage.prototype.getMessageCase = function() {
  return /** @type {proto.ServerMessage.MessageCase} */(jspb.Message.computeOneofCase(this, proto.ServerMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ServerMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.ServerMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ServerMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    arduinoconnectedmessage: (f = msg.getArduinoconnectedmessage()) && proto.ArduinoConnected.toObject(includeInstance, f),
    clientconnectedmessage: (f = msg.getClientconnectedmessage()) && proto.ClientConnected.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ServerMessage}
 */
proto.ServerMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ServerMessage;
  return proto.ServerMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ServerMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ServerMessage}
 */
proto.ServerMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ArduinoConnected;
      reader.readMessage(value,proto.ArduinoConnected.deserializeBinaryFromReader);
      msg.setArduinoconnectedmessage(value);
      break;
    case 2:
      var value = new proto.ClientConnected;
      reader.readMessage(value,proto.ClientConnected.deserializeBinaryFromReader);
      msg.setClientconnectedmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ServerMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ServerMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ServerMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ServerMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArduinoconnectedmessage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ArduinoConnected.serializeBinaryToWriter
    );
  }
  f = message.getClientconnectedmessage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ClientConnected.serializeBinaryToWriter
    );
  }
};


/**
 * optional ArduinoConnected arduinoConnectedMessage = 1;
 * @return {?proto.ArduinoConnected}
 */
proto.ServerMessage.prototype.getArduinoconnectedmessage = function() {
  return /** @type{?proto.ArduinoConnected} */ (
    jspb.Message.getWrapperField(this, proto.ArduinoConnected, 1));
};


/** @param {?proto.ArduinoConnected|undefined} value */
proto.ServerMessage.prototype.setArduinoconnectedmessage = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.ServerMessage.oneofGroups_[0], value);
};


proto.ServerMessage.prototype.clearArduinoconnectedmessage = function() {
  this.setArduinoconnectedmessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ServerMessage.prototype.hasArduinoconnectedmessage = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ClientConnected clientConnectedMessage = 2;
 * @return {?proto.ClientConnected}
 */
proto.ServerMessage.prototype.getClientconnectedmessage = function() {
  return /** @type{?proto.ClientConnected} */ (
    jspb.Message.getWrapperField(this, proto.ClientConnected, 2));
};


/** @param {?proto.ClientConnected|undefined} value */
proto.ServerMessage.prototype.setClientconnectedmessage = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.ServerMessage.oneofGroups_[0], value);
};


proto.ServerMessage.prototype.clearClientconnectedmessage = function() {
  this.setClientconnectedmessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ServerMessage.prototype.hasClientconnectedmessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


