// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/ClientSocketMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Protos/ClientSocketMessages.proto</summary>
public static partial class ClientSocketMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for Protos/ClientSocketMessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ClientSocketMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiFQcm90b3MvQ2xpZW50U29ja2V0TWVzc2FnZXMucHJvdG8ilQEKEU1lc3Nh",
          "Z2VGcm9tQ2xpZW50Eh8KCmNsaWVudFR5cGUYASABKA4yCy5DbGllbnRUeXBl",
          "EicKDWFyZHVpbm9BY3Rpb24YAiABKAsyDi5BcmR1aW5vQWN0aW9uSAASKwoP",
          "d2ViQ2xpZW50QWN0aW9uGAMgASgLMhAuV2ViQ2xpZW50QWN0aW9uSABCCQoH",
          "bWVzc2FnZSJ2Cg1BcmR1aW5vQWN0aW9uEiMKC2FyZHVpbm9Kb2luGAEgASgL",
          "MgwuQXJkdWlub0pvaW5IABI1ChRhcmR1aW5vV29ya291dEFjdGlvbhgCIAEo",
          "CzIVLkFyZHVpbm9Xb3Jrb3V0QWN0aW9uSABCCQoHbWVzc2FnZSIyCgtBcmR1",
          "aW5vSm9pbhIRCglhcmR1aW5vSWQYASABKAUSEAoIcmZJZENhcmQYAiABKAUi",
          "TQoGTG9nb3V0EhIKCnJmSWRDYXJkTm8YASABKAUSDwoHbWFjaGluZRgCIAEo",
          "BRILCgNzZXQYAyABKAUSEQoJcmVzdFRpbWVyGAQgASgFIiUKA1NldBILCgNz",
          "ZXQYASABKAUSEQoJcmVzdFRpbWVyGAIgASgFIowBChRBcmR1aW5vV29ya291",
          "dEFjdGlvbhIJCgFuGAEgASgFEhUKDXBvd2VyQ29udHJhY3QYAiABKAUSDgoG",
          "d2VpZ2h0GAMgASgFEgsKA3NldBgEIAEoBRIQCghjb250cmFjdBgFIAEoBRIS",
          "CgpyZklkQ2FyZE5vGAYgASgFEg8KB21hY2hpbmUYByABKAUiKgoFWHRlbmQS",
          "DQoFeHRlbmQYASABKAUSEgoKcG93ZXJYdGVuZBgCIAEoBSJRCg9XZWJDbGll",
          "bnRBY3Rpb24SMwoTd2ViQ2xpZW50QWN0aW9uSm9pbhgBIAEoCzIULldlYkNs",
          "aWVudEFjdGlvbkpvaW5IAEIJCgdtZXNzYWdlIikKE1dlYkNsaWVudEFjdGlv",
          "bkpvaW4SEgoKcmZJZENhcmRObxgBIAEoBSowCgpDbGllbnRUeXBlEhIKDkFS",
          "RFVJTk9fQ0xJRU5UEAASDgoKV0VCX0NMSUVOVBABYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ClientType), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MessageFromClient), global::MessageFromClient.Parser, new[]{ "ClientType", "ArduinoAction", "WebClientAction" }, new[]{ "Message" }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ArduinoAction), global::ArduinoAction.Parser, new[]{ "ArduinoJoin", "ArduinoWorkoutAction" }, new[]{ "Message" }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ArduinoJoin), global::ArduinoJoin.Parser, new[]{ "ArduinoId", "RfIdCard" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Logout), global::Logout.Parser, new[]{ "RfIdCardNo", "Machine", "Set", "RestTimer" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Set), global::Set.Parser, new[]{ "Set_", "RestTimer" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ArduinoWorkoutAction), global::ArduinoWorkoutAction.Parser, new[]{ "N", "PowerContract", "Weight", "Set", "Contract", "RfIdCardNo", "Machine" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Xtend), global::Xtend.Parser, new[]{ "Xtend_", "PowerXtend" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WebClientAction), global::WebClientAction.Parser, new[]{ "WebClientActionJoin" }, new[]{ "Message" }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::WebClientActionJoin), global::WebClientActionJoin.Parser, new[]{ "RfIdCardNo" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ClientType {
  [pbr::OriginalName("ARDUINO_CLIENT")] ArduinoClient = 0,
  [pbr::OriginalName("WEB_CLIENT")] WebClient = 1,
}

#endregion

#region Messages
public sealed partial class MessageFromClient : pb::IMessage<MessageFromClient> {
  private static readonly pb::MessageParser<MessageFromClient> _parser = new pb::MessageParser<MessageFromClient>(() => new MessageFromClient());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MessageFromClient> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MessageFromClient() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MessageFromClient(MessageFromClient other) : this() {
    clientType_ = other.clientType_;
    switch (other.MessageCase) {
      case MessageOneofCase.ArduinoAction:
        ArduinoAction = other.ArduinoAction.Clone();
        break;
      case MessageOneofCase.WebClientAction:
        WebClientAction = other.WebClientAction.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MessageFromClient Clone() {
    return new MessageFromClient(this);
  }

  /// <summary>Field number for the "clientType" field.</summary>
  public const int ClientTypeFieldNumber = 1;
  private global::ClientType clientType_ = 0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ClientType ClientType {
    get { return clientType_; }
    set {
      clientType_ = value;
    }
  }

  /// <summary>Field number for the "arduinoAction" field.</summary>
  public const int ArduinoActionFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ArduinoAction ArduinoAction {
    get { return messageCase_ == MessageOneofCase.ArduinoAction ? (global::ArduinoAction) message_ : null; }
    set {
      message_ = value;
      messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ArduinoAction;
    }
  }

  /// <summary>Field number for the "webClientAction" field.</summary>
  public const int WebClientActionFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::WebClientAction WebClientAction {
    get { return messageCase_ == MessageOneofCase.WebClientAction ? (global::WebClientAction) message_ : null; }
    set {
      message_ = value;
      messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.WebClientAction;
    }
  }

  private object message_;
  /// <summary>Enum of possible cases for the "message" oneof.</summary>
  public enum MessageOneofCase {
    None = 0,
    ArduinoAction = 2,
    WebClientAction = 3,
  }
  private MessageOneofCase messageCase_ = MessageOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MessageOneofCase MessageCase {
    get { return messageCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMessage() {
    messageCase_ = MessageOneofCase.None;
    message_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MessageFromClient);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MessageFromClient other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ClientType != other.ClientType) return false;
    if (!object.Equals(ArduinoAction, other.ArduinoAction)) return false;
    if (!object.Equals(WebClientAction, other.WebClientAction)) return false;
    if (MessageCase != other.MessageCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ClientType != 0) hash ^= ClientType.GetHashCode();
    if (messageCase_ == MessageOneofCase.ArduinoAction) hash ^= ArduinoAction.GetHashCode();
    if (messageCase_ == MessageOneofCase.WebClientAction) hash ^= WebClientAction.GetHashCode();
    hash ^= (int) messageCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ClientType != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ClientType);
    }
    if (messageCase_ == MessageOneofCase.ArduinoAction) {
      output.WriteRawTag(18);
      output.WriteMessage(ArduinoAction);
    }
    if (messageCase_ == MessageOneofCase.WebClientAction) {
      output.WriteRawTag(26);
      output.WriteMessage(WebClientAction);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ClientType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ClientType);
    }
    if (messageCase_ == MessageOneofCase.ArduinoAction) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArduinoAction);
    }
    if (messageCase_ == MessageOneofCase.WebClientAction) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(WebClientAction);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MessageFromClient other) {
    if (other == null) {
      return;
    }
    if (other.ClientType != 0) {
      ClientType = other.ClientType;
    }
    switch (other.MessageCase) {
      case MessageOneofCase.ArduinoAction:
        if (ArduinoAction == null) {
          ArduinoAction = new global::ArduinoAction();
        }
        ArduinoAction.MergeFrom(other.ArduinoAction);
        break;
      case MessageOneofCase.WebClientAction:
        if (WebClientAction == null) {
          WebClientAction = new global::WebClientAction();
        }
        WebClientAction.MergeFrom(other.WebClientAction);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          clientType_ = (global::ClientType) input.ReadEnum();
          break;
        }
        case 18: {
          global::ArduinoAction subBuilder = new global::ArduinoAction();
          if (messageCase_ == MessageOneofCase.ArduinoAction) {
            subBuilder.MergeFrom(ArduinoAction);
          }
          input.ReadMessage(subBuilder);
          ArduinoAction = subBuilder;
          break;
        }
        case 26: {
          global::WebClientAction subBuilder = new global::WebClientAction();
          if (messageCase_ == MessageOneofCase.WebClientAction) {
            subBuilder.MergeFrom(WebClientAction);
          }
          input.ReadMessage(subBuilder);
          WebClientAction = subBuilder;
          break;
        }
      }
    }
  }

}

public sealed partial class ArduinoAction : pb::IMessage<ArduinoAction> {
  private static readonly pb::MessageParser<ArduinoAction> _parser = new pb::MessageParser<ArduinoAction>(() => new ArduinoAction());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ArduinoAction> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoAction() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoAction(ArduinoAction other) : this() {
    switch (other.MessageCase) {
      case MessageOneofCase.ArduinoJoin:
        ArduinoJoin = other.ArduinoJoin.Clone();
        break;
      case MessageOneofCase.ArduinoWorkoutAction:
        ArduinoWorkoutAction = other.ArduinoWorkoutAction.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoAction Clone() {
    return new ArduinoAction(this);
  }

  /// <summary>Field number for the "arduinoJoin" field.</summary>
  public const int ArduinoJoinFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ArduinoJoin ArduinoJoin {
    get { return messageCase_ == MessageOneofCase.ArduinoJoin ? (global::ArduinoJoin) message_ : null; }
    set {
      message_ = value;
      messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ArduinoJoin;
    }
  }

  /// <summary>Field number for the "arduinoWorkoutAction" field.</summary>
  public const int ArduinoWorkoutActionFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ArduinoWorkoutAction ArduinoWorkoutAction {
    get { return messageCase_ == MessageOneofCase.ArduinoWorkoutAction ? (global::ArduinoWorkoutAction) message_ : null; }
    set {
      message_ = value;
      messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.ArduinoWorkoutAction;
    }
  }

  private object message_;
  /// <summary>Enum of possible cases for the "message" oneof.</summary>
  public enum MessageOneofCase {
    None = 0,
    ArduinoJoin = 1,
    ArduinoWorkoutAction = 2,
  }
  private MessageOneofCase messageCase_ = MessageOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MessageOneofCase MessageCase {
    get { return messageCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMessage() {
    messageCase_ = MessageOneofCase.None;
    message_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ArduinoAction);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ArduinoAction other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ArduinoJoin, other.ArduinoJoin)) return false;
    if (!object.Equals(ArduinoWorkoutAction, other.ArduinoWorkoutAction)) return false;
    if (MessageCase != other.MessageCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (messageCase_ == MessageOneofCase.ArduinoJoin) hash ^= ArduinoJoin.GetHashCode();
    if (messageCase_ == MessageOneofCase.ArduinoWorkoutAction) hash ^= ArduinoWorkoutAction.GetHashCode();
    hash ^= (int) messageCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (messageCase_ == MessageOneofCase.ArduinoJoin) {
      output.WriteRawTag(10);
      output.WriteMessage(ArduinoJoin);
    }
    if (messageCase_ == MessageOneofCase.ArduinoWorkoutAction) {
      output.WriteRawTag(18);
      output.WriteMessage(ArduinoWorkoutAction);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (messageCase_ == MessageOneofCase.ArduinoJoin) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArduinoJoin);
    }
    if (messageCase_ == MessageOneofCase.ArduinoWorkoutAction) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArduinoWorkoutAction);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ArduinoAction other) {
    if (other == null) {
      return;
    }
    switch (other.MessageCase) {
      case MessageOneofCase.ArduinoJoin:
        if (ArduinoJoin == null) {
          ArduinoJoin = new global::ArduinoJoin();
        }
        ArduinoJoin.MergeFrom(other.ArduinoJoin);
        break;
      case MessageOneofCase.ArduinoWorkoutAction:
        if (ArduinoWorkoutAction == null) {
          ArduinoWorkoutAction = new global::ArduinoWorkoutAction();
        }
        ArduinoWorkoutAction.MergeFrom(other.ArduinoWorkoutAction);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::ArduinoJoin subBuilder = new global::ArduinoJoin();
          if (messageCase_ == MessageOneofCase.ArduinoJoin) {
            subBuilder.MergeFrom(ArduinoJoin);
          }
          input.ReadMessage(subBuilder);
          ArduinoJoin = subBuilder;
          break;
        }
        case 18: {
          global::ArduinoWorkoutAction subBuilder = new global::ArduinoWorkoutAction();
          if (messageCase_ == MessageOneofCase.ArduinoWorkoutAction) {
            subBuilder.MergeFrom(ArduinoWorkoutAction);
          }
          input.ReadMessage(subBuilder);
          ArduinoWorkoutAction = subBuilder;
          break;
        }
      }
    }
  }

}

public sealed partial class ArduinoJoin : pb::IMessage<ArduinoJoin> {
  private static readonly pb::MessageParser<ArduinoJoin> _parser = new pb::MessageParser<ArduinoJoin>(() => new ArduinoJoin());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ArduinoJoin> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoJoin() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoJoin(ArduinoJoin other) : this() {
    arduinoId_ = other.arduinoId_;
    rfIdCard_ = other.rfIdCard_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoJoin Clone() {
    return new ArduinoJoin(this);
  }

  /// <summary>Field number for the "arduinoId" field.</summary>
  public const int ArduinoIdFieldNumber = 1;
  private int arduinoId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ArduinoId {
    get { return arduinoId_; }
    set {
      arduinoId_ = value;
    }
  }

  /// <summary>Field number for the "rfIdCard" field.</summary>
  public const int RfIdCardFieldNumber = 2;
  private int rfIdCard_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RfIdCard {
    get { return rfIdCard_; }
    set {
      rfIdCard_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ArduinoJoin);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ArduinoJoin other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ArduinoId != other.ArduinoId) return false;
    if (RfIdCard != other.RfIdCard) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ArduinoId != 0) hash ^= ArduinoId.GetHashCode();
    if (RfIdCard != 0) hash ^= RfIdCard.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ArduinoId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ArduinoId);
    }
    if (RfIdCard != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(RfIdCard);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ArduinoId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ArduinoId);
    }
    if (RfIdCard != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RfIdCard);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ArduinoJoin other) {
    if (other == null) {
      return;
    }
    if (other.ArduinoId != 0) {
      ArduinoId = other.ArduinoId;
    }
    if (other.RfIdCard != 0) {
      RfIdCard = other.RfIdCard;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ArduinoId = input.ReadInt32();
          break;
        }
        case 16: {
          RfIdCard = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class Logout : pb::IMessage<Logout> {
  private static readonly pb::MessageParser<Logout> _parser = new pb::MessageParser<Logout>(() => new Logout());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Logout> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Logout() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Logout(Logout other) : this() {
    rfIdCardNo_ = other.rfIdCardNo_;
    machine_ = other.machine_;
    set_ = other.set_;
    restTimer_ = other.restTimer_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Logout Clone() {
    return new Logout(this);
  }

  /// <summary>Field number for the "rfIdCardNo" field.</summary>
  public const int RfIdCardNoFieldNumber = 1;
  private int rfIdCardNo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RfIdCardNo {
    get { return rfIdCardNo_; }
    set {
      rfIdCardNo_ = value;
    }
  }

  /// <summary>Field number for the "machine" field.</summary>
  public const int MachineFieldNumber = 2;
  private int machine_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Machine {
    get { return machine_; }
    set {
      machine_ = value;
    }
  }

  /// <summary>Field number for the "set" field.</summary>
  public const int SetFieldNumber = 3;
  private int set_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Set {
    get { return set_; }
    set {
      set_ = value;
    }
  }

  /// <summary>Field number for the "restTimer" field.</summary>
  public const int RestTimerFieldNumber = 4;
  private int restTimer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RestTimer {
    get { return restTimer_; }
    set {
      restTimer_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Logout);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Logout other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RfIdCardNo != other.RfIdCardNo) return false;
    if (Machine != other.Machine) return false;
    if (Set != other.Set) return false;
    if (RestTimer != other.RestTimer) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (RfIdCardNo != 0) hash ^= RfIdCardNo.GetHashCode();
    if (Machine != 0) hash ^= Machine.GetHashCode();
    if (Set != 0) hash ^= Set.GetHashCode();
    if (RestTimer != 0) hash ^= RestTimer.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (RfIdCardNo != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RfIdCardNo);
    }
    if (Machine != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Machine);
    }
    if (Set != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Set);
    }
    if (RestTimer != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(RestTimer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (RfIdCardNo != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RfIdCardNo);
    }
    if (Machine != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Machine);
    }
    if (Set != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Set);
    }
    if (RestTimer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RestTimer);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Logout other) {
    if (other == null) {
      return;
    }
    if (other.RfIdCardNo != 0) {
      RfIdCardNo = other.RfIdCardNo;
    }
    if (other.Machine != 0) {
      Machine = other.Machine;
    }
    if (other.Set != 0) {
      Set = other.Set;
    }
    if (other.RestTimer != 0) {
      RestTimer = other.RestTimer;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RfIdCardNo = input.ReadInt32();
          break;
        }
        case 16: {
          Machine = input.ReadInt32();
          break;
        }
        case 24: {
          Set = input.ReadInt32();
          break;
        }
        case 32: {
          RestTimer = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class Set : pb::IMessage<Set> {
  private static readonly pb::MessageParser<Set> _parser = new pb::MessageParser<Set>(() => new Set());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Set> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Set() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Set(Set other) : this() {
    set_ = other.set_;
    restTimer_ = other.restTimer_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Set Clone() {
    return new Set(this);
  }

  /// <summary>Field number for the "set" field.</summary>
  public const int Set_FieldNumber = 1;
  private int set_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Set_ {
    get { return set_; }
    set {
      set_ = value;
    }
  }

  /// <summary>Field number for the "restTimer" field.</summary>
  public const int RestTimerFieldNumber = 2;
  private int restTimer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RestTimer {
    get { return restTimer_; }
    set {
      restTimer_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Set);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Set other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Set_ != other.Set_) return false;
    if (RestTimer != other.RestTimer) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Set_ != 0) hash ^= Set_.GetHashCode();
    if (RestTimer != 0) hash ^= RestTimer.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Set_ != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Set_);
    }
    if (RestTimer != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(RestTimer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Set_ != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Set_);
    }
    if (RestTimer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RestTimer);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Set other) {
    if (other == null) {
      return;
    }
    if (other.Set_ != 0) {
      Set_ = other.Set_;
    }
    if (other.RestTimer != 0) {
      RestTimer = other.RestTimer;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Set_ = input.ReadInt32();
          break;
        }
        case 16: {
          RestTimer = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class ArduinoWorkoutAction : pb::IMessage<ArduinoWorkoutAction> {
  private static readonly pb::MessageParser<ArduinoWorkoutAction> _parser = new pb::MessageParser<ArduinoWorkoutAction>(() => new ArduinoWorkoutAction());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ArduinoWorkoutAction> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoWorkoutAction() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoWorkoutAction(ArduinoWorkoutAction other) : this() {
    n_ = other.n_;
    powerContract_ = other.powerContract_;
    weight_ = other.weight_;
    set_ = other.set_;
    contract_ = other.contract_;
    rfIdCardNo_ = other.rfIdCardNo_;
    machine_ = other.machine_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ArduinoWorkoutAction Clone() {
    return new ArduinoWorkoutAction(this);
  }

  /// <summary>Field number for the "n" field.</summary>
  public const int NFieldNumber = 1;
  private int n_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int N {
    get { return n_; }
    set {
      n_ = value;
    }
  }

  /// <summary>Field number for the "powerContract" field.</summary>
  public const int PowerContractFieldNumber = 2;
  private int powerContract_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PowerContract {
    get { return powerContract_; }
    set {
      powerContract_ = value;
    }
  }

  /// <summary>Field number for the "weight" field.</summary>
  public const int WeightFieldNumber = 3;
  private int weight_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Weight {
    get { return weight_; }
    set {
      weight_ = value;
    }
  }

  /// <summary>Field number for the "set" field.</summary>
  public const int SetFieldNumber = 4;
  private int set_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Set {
    get { return set_; }
    set {
      set_ = value;
    }
  }

  /// <summary>Field number for the "contract" field.</summary>
  public const int ContractFieldNumber = 5;
  private int contract_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Contract {
    get { return contract_; }
    set {
      contract_ = value;
    }
  }

  /// <summary>Field number for the "rfIdCardNo" field.</summary>
  public const int RfIdCardNoFieldNumber = 6;
  private int rfIdCardNo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RfIdCardNo {
    get { return rfIdCardNo_; }
    set {
      rfIdCardNo_ = value;
    }
  }

  /// <summary>Field number for the "machine" field.</summary>
  public const int MachineFieldNumber = 7;
  private int machine_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Machine {
    get { return machine_; }
    set {
      machine_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ArduinoWorkoutAction);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ArduinoWorkoutAction other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (N != other.N) return false;
    if (PowerContract != other.PowerContract) return false;
    if (Weight != other.Weight) return false;
    if (Set != other.Set) return false;
    if (Contract != other.Contract) return false;
    if (RfIdCardNo != other.RfIdCardNo) return false;
    if (Machine != other.Machine) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (N != 0) hash ^= N.GetHashCode();
    if (PowerContract != 0) hash ^= PowerContract.GetHashCode();
    if (Weight != 0) hash ^= Weight.GetHashCode();
    if (Set != 0) hash ^= Set.GetHashCode();
    if (Contract != 0) hash ^= Contract.GetHashCode();
    if (RfIdCardNo != 0) hash ^= RfIdCardNo.GetHashCode();
    if (Machine != 0) hash ^= Machine.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (N != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(N);
    }
    if (PowerContract != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PowerContract);
    }
    if (Weight != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Weight);
    }
    if (Set != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Set);
    }
    if (Contract != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Contract);
    }
    if (RfIdCardNo != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(RfIdCardNo);
    }
    if (Machine != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Machine);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (N != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(N);
    }
    if (PowerContract != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PowerContract);
    }
    if (Weight != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Weight);
    }
    if (Set != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Set);
    }
    if (Contract != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Contract);
    }
    if (RfIdCardNo != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RfIdCardNo);
    }
    if (Machine != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Machine);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ArduinoWorkoutAction other) {
    if (other == null) {
      return;
    }
    if (other.N != 0) {
      N = other.N;
    }
    if (other.PowerContract != 0) {
      PowerContract = other.PowerContract;
    }
    if (other.Weight != 0) {
      Weight = other.Weight;
    }
    if (other.Set != 0) {
      Set = other.Set;
    }
    if (other.Contract != 0) {
      Contract = other.Contract;
    }
    if (other.RfIdCardNo != 0) {
      RfIdCardNo = other.RfIdCardNo;
    }
    if (other.Machine != 0) {
      Machine = other.Machine;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          N = input.ReadInt32();
          break;
        }
        case 16: {
          PowerContract = input.ReadInt32();
          break;
        }
        case 24: {
          Weight = input.ReadInt32();
          break;
        }
        case 32: {
          Set = input.ReadInt32();
          break;
        }
        case 40: {
          Contract = input.ReadInt32();
          break;
        }
        case 48: {
          RfIdCardNo = input.ReadInt32();
          break;
        }
        case 56: {
          Machine = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class Xtend : pb::IMessage<Xtend> {
  private static readonly pb::MessageParser<Xtend> _parser = new pb::MessageParser<Xtend>(() => new Xtend());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Xtend> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Xtend() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Xtend(Xtend other) : this() {
    xtend_ = other.xtend_;
    powerXtend_ = other.powerXtend_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Xtend Clone() {
    return new Xtend(this);
  }

  /// <summary>Field number for the "xtend" field.</summary>
  public const int Xtend_FieldNumber = 1;
  private int xtend_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Xtend_ {
    get { return xtend_; }
    set {
      xtend_ = value;
    }
  }

  /// <summary>Field number for the "powerXtend" field.</summary>
  public const int PowerXtendFieldNumber = 2;
  private int powerXtend_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PowerXtend {
    get { return powerXtend_; }
    set {
      powerXtend_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Xtend);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Xtend other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Xtend_ != other.Xtend_) return false;
    if (PowerXtend != other.PowerXtend) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Xtend_ != 0) hash ^= Xtend_.GetHashCode();
    if (PowerXtend != 0) hash ^= PowerXtend.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Xtend_ != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Xtend_);
    }
    if (PowerXtend != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PowerXtend);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Xtend_ != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Xtend_);
    }
    if (PowerXtend != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PowerXtend);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Xtend other) {
    if (other == null) {
      return;
    }
    if (other.Xtend_ != 0) {
      Xtend_ = other.Xtend_;
    }
    if (other.PowerXtend != 0) {
      PowerXtend = other.PowerXtend;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Xtend_ = input.ReadInt32();
          break;
        }
        case 16: {
          PowerXtend = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class WebClientAction : pb::IMessage<WebClientAction> {
  private static readonly pb::MessageParser<WebClientAction> _parser = new pb::MessageParser<WebClientAction>(() => new WebClientAction());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WebClientAction> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WebClientAction() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WebClientAction(WebClientAction other) : this() {
    switch (other.MessageCase) {
      case MessageOneofCase.WebClientActionJoin:
        WebClientActionJoin = other.WebClientActionJoin.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WebClientAction Clone() {
    return new WebClientAction(this);
  }

  /// <summary>Field number for the "webClientActionJoin" field.</summary>
  public const int WebClientActionJoinFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::WebClientActionJoin WebClientActionJoin {
    get { return messageCase_ == MessageOneofCase.WebClientActionJoin ? (global::WebClientActionJoin) message_ : null; }
    set {
      message_ = value;
      messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.WebClientActionJoin;
    }
  }

  private object message_;
  /// <summary>Enum of possible cases for the "message" oneof.</summary>
  public enum MessageOneofCase {
    None = 0,
    WebClientActionJoin = 1,
  }
  private MessageOneofCase messageCase_ = MessageOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MessageOneofCase MessageCase {
    get { return messageCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearMessage() {
    messageCase_ = MessageOneofCase.None;
    message_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WebClientAction);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WebClientAction other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(WebClientActionJoin, other.WebClientActionJoin)) return false;
    if (MessageCase != other.MessageCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (messageCase_ == MessageOneofCase.WebClientActionJoin) hash ^= WebClientActionJoin.GetHashCode();
    hash ^= (int) messageCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (messageCase_ == MessageOneofCase.WebClientActionJoin) {
      output.WriteRawTag(10);
      output.WriteMessage(WebClientActionJoin);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (messageCase_ == MessageOneofCase.WebClientActionJoin) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(WebClientActionJoin);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WebClientAction other) {
    if (other == null) {
      return;
    }
    switch (other.MessageCase) {
      case MessageOneofCase.WebClientActionJoin:
        if (WebClientActionJoin == null) {
          WebClientActionJoin = new global::WebClientActionJoin();
        }
        WebClientActionJoin.MergeFrom(other.WebClientActionJoin);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::WebClientActionJoin subBuilder = new global::WebClientActionJoin();
          if (messageCase_ == MessageOneofCase.WebClientActionJoin) {
            subBuilder.MergeFrom(WebClientActionJoin);
          }
          input.ReadMessage(subBuilder);
          WebClientActionJoin = subBuilder;
          break;
        }
      }
    }
  }

}

public sealed partial class WebClientActionJoin : pb::IMessage<WebClientActionJoin> {
  private static readonly pb::MessageParser<WebClientActionJoin> _parser = new pb::MessageParser<WebClientActionJoin>(() => new WebClientActionJoin());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<WebClientActionJoin> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ClientSocketMessagesReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WebClientActionJoin() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WebClientActionJoin(WebClientActionJoin other) : this() {
    rfIdCardNo_ = other.rfIdCardNo_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public WebClientActionJoin Clone() {
    return new WebClientActionJoin(this);
  }

  /// <summary>Field number for the "rfIdCardNo" field.</summary>
  public const int RfIdCardNoFieldNumber = 1;
  private int rfIdCardNo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RfIdCardNo {
    get { return rfIdCardNo_; }
    set {
      rfIdCardNo_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as WebClientActionJoin);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(WebClientActionJoin other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RfIdCardNo != other.RfIdCardNo) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (RfIdCardNo != 0) hash ^= RfIdCardNo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (RfIdCardNo != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RfIdCardNo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (RfIdCardNo != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RfIdCardNo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(WebClientActionJoin other) {
    if (other == null) {
      return;
    }
    if (other.RfIdCardNo != 0) {
      RfIdCardNo = other.RfIdCardNo;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RfIdCardNo = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
